spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: true
    database-platform: H2
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    driver-class-name: org.h2.Driver

logging:
  level:
    ma.glasnost.orika: info
    org:
      hibernate: info
      SQL: debug
      type: trace

    java:
      sql: info

    jdbc:
      sqltiming: debug
      resultsettable: debug
---
spring:
  profiles: local
  csrf-enabled: false

---
spring:
  profiles: test
  csrf-enabled: false
